### PR TITLE
docs: fix PDF data source link in Overview

### PR DESCRIPTION
**Pull request by jhony112**
[DataSources Pdf link](https://llm-tools.mintlify.app/components/data-sources/overview) currently points to a wrong url, this fixes the href reference

## Description

Old url  on overview page for DataSources points to `components/data-sources/pdf-file`   should be : `components/data-sources/pdf`

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
-   [x] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new tsc or eslint warnings
-   [x] I have ran tests that prove my fix is effective or that my feature works
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] My changes do not result in new npm audit errors

### CODE REVIEW

**Comment by adhityan** [comment]
Thank you for the fix.

**Comment by adhityan** [comment]
The project follows conventional commit standards. Could you amend your commit messages to follow this pattern? Read more here - https://www.conventionalcommits.org/en/v1.0.0

I think in your case, you need to remove the space between the `:` and `docs`. Sorry to have this enforced but all the other build tools work with this standard.

**Comment by jhony112** [comment]
@adhityan should be fixed now

**Comment by adhityan** [comment]
Great. LGTM.

**Pull request merged**
